# netlify.toml

# Build settings
[build]
  publish = "public"
  command = "bundle exec rake assets:precompile"
  base = "public"  # Specify the base directory

# Environment variables
[build.environment]
  RAILS_ENV = "production"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
